### ISSUE TITLE
Completion doesn't work well on ST3

### ISSUE THREAD

**Issue by mehrancodes** [james2doyle/laravel-helper-completions#2]
I used to have issues getting auto completes of this plugin in Sublime Text 3 to work for Laravel. I realized this was because by default sublime needs the opening <?php and closing ?> tags for a file which we don’t usually use it for blade engine.
may you write a guide on how to fix this problem for `laravel helper`  ?
Thanks!

**Comment by james2doyle** [comment]
I'm not well-versed in the way sublime works with the scopes. So I am not sure what needs to change in order to make this work in Laravel Blade.

**Comment by james2doyle** [comment]
Ok I pushed some updates that should allow the helpers to complete in blade syntax. This does require that [Medalink/laravel-blade](https://github.com/Medalink/laravel-blade) is installed.

**Comment by mehrancodes** [comment]
Ya that semicolon was extra in the `contents`
Thank you!! :+1
